[project]
name = "emanuel"
version = "0.0.0"
description = "A configurable discord bot with a LLM pipeline integration"
authors = [{ name="Mathis Siebert" }]
readme = "README.md"
license-files = [
    "LICENSE"
]
requires-python = ">=3.13"
dependencies = [
  "py-cord>=2.6",
  "edgygraph>=0.0.89",
  "edgynodes>=0.0.103",
]

[project.optional-dependencies]
openai = ["openai"]
ollama = ["ollama"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"